backend:
  name: git-gateway
  branch: master

media_folder: "client/public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: 'page'
    label: 'Page'
    folder: "_posts/page"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}